### ISSUE TITLE
CI build failing for release/core_1.0rc/0.2

### ISSUE THREAD

**Issue by ThomasKroes** [ManiVaultStudio/SpaceWalker#4]
The CI build for [release/core_1.0rc/0.2](https://github.com/ManiVaultStudio/SpaceWalker/tree/release/core_1.0rc/0.2) is [failing](https://github.com/ManiVaultStudio/SpaceWalker/actions/runs/8122542960/job/22202086955):

```
-- QUERY ERROR RESULT:
items.find(
	{
		"repo":{"$eq" : "conan-local"},
		"name":{"$eq" : "conaninfo.txt"},
		"@conan.package.user": {"$eq" : "lkeb"},
CMake Error at cmake/InstallArtifactoryPackage.cmake:67 (message):
  No matching artifactory packages found.  Please check the query.
Call Stack (most recent call first):
  cmake/InstallArtifactoryPackage.cmake:105 (find_artifactory_package)
  cmake/InstallArtifactoryPackage.cmake:171 (get_artifactory_package)
  CMakeLists.txt:162 (install_artifactory_package)


		"@conan.package.channel": {"$eq" : "stable"},
		"@conan.package.name": {"$eq" : "faiss"},
		"@conan.package.version": {"$eq" : "1.7.3"},
		"@conan.settings.os": {"$eq" : "Linux"},
		"@conan.settings.compiler": {"$eq" : "gcc"},
		"@conan.settings.compiler.version": {"$match" : "11*"}
	}
)
-- Configuring incomplete, errors occurred!
SpaceWalker/0.2@lkeb/stable: 
SpaceWalker/0.2@lkeb/stable: WARN: There are uncommitted changes, skipping the replacement of 'scm.url' and 'scm.revision' auto fields. Use --ignore-dirty to force it. The 'conan upload' command will prevent uploading recipes with 'auto' values in these fields.
SpaceWalker/0.2@lkeb/stable: ERROR: Package 'fb77e92815a70b44df67dd1e39119092d04dc5b7' build failed
SpaceWalker/0.2@lkeb/stable: WARN: Build folder /home/runner/work/SpaceWalker/SpaceWalker/_conan/.conan/data/SpaceWalker/0.2/lkeb/stable/build/fb77e92815a70b44df67dd1e39119092d04dc5b7
ERROR: SpaceWalker/0.2@lkeb/stable: Error in build() method, line 120
	cmake = self._configure_cmake()
while calling '_configure_cmake', line 102
	cmake.configure(build_script_folder="hdps/SpaceWalker")
	ConanException: Error 1 while executing cmake -G "Ninja Multi-Config" -DCMAKE_TOOLCHAIN_FILE="/home/runner/work/SpaceWalker/SpaceWalker/_conan/.conan/data/SpaceWalker/0.2/lkeb/stable/build/fb77e92815a70b44df67dd1e39119092d04dc5b7/conan_toolchain.cmake" -DCMAKE_INSTALL_PREFIX="/home/runner/work/SpaceWalker/SpaceWalker/_conan/.conan/data/SpaceWalker/0.2/lkeb/stable/package/fb77e92815a70b44df67dd1e39119092d04dc5b7" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" "/home/runner/work/SpaceWalker/SpaceWalker/_conan/.conan/data/SpaceWalker/0.2/lkeb/stable/build/fb77e92815a70b44df67dd1e39119092d04dc5b7/hdps/SpaceWalker"
Error: Process completed with exit code 1.
```
, despite the changes below:
```
matrix:
    include:
      - name: Windows-msvc2019
        os: windows-2019
        compiler: msvc-2019
        build-cversion: 16
        build-runtime: MD
        build-config: Release
      - name: Linux_gcc11
        os: ubuntu-22.04
        build-cc: gcc
        build-cxx: g++
        build-compiler: gcc
        build-cversion: 11
        build-config: Release
        build-os: Linux
        build-libcxx: libstdc++
      - name: Macos_xcode13.4
        os: macos-12
        build-compiler: apple-clang
        build-cversion: 13
        build-config: Release
        build-os: Macos
        build-xcode-version: 13.4
        build-libcxx: libc++
```
